name: "Fetch Secrets from AWS Secrets Manager"
description: "Retrieve a secret JSON from AWS Secrets Manager and export its keys as env variables"

inputs:
  role-to-assume:
    description: "AWS role to assume"
    required: true
  aws_region:
    description: "AWS Region"
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.AWS_ASSUME_ROLE }}
        aws-region: ${{ inputs.AWS_REGION }}

    - name: Fetch Secrets from AWS Secrets Manager
      shell: bash
      run: |
        secret_json=$(aws secretsmanager get-secret-value --secret-id "${{ inputs.secret_id }}" --query SecretString --output text)
        # export each key as environment variable
        for key in $(echo "$secret_json" | jq -r 'keys[]'); do
          value=$(echo "$secret_json" | jq -r ".\"$key\"")
          echo "$key=$value" >> $GITHUB_ENV
        done
