name: "Fetch Secrets from AWS Secrets Manager"
description: "Retrieve a secret JSON from AWS Secrets Manager and export its keys as env variables"

inputs:
  aws_access_key_id:
    description: "AWS Access Key ID"
    required: true
  aws_secret_access_key:
    description: "AWS Secret Access Key"
    required: true
  aws_region:
    description: "AWS Region"
    required: true
  secret_id:
    description: "AWS Secrets Manager Secret ID"
    required: true

runs:
  using: "composite"
  steps:
    # 1. Configure AWS CLI environment
    - name: Configure AWS CLI
      shell: bash
      run: |
        if [ -z "${{ inputs.aws_access_key_id }}" ] || [ -z "${{ inputs.aws_secret_access_key }}" ] || [ -z "${{ inputs.aws_region }}" ] || [ -z "${{ inputs.secret_id }}" ]; then
          echo "Missing required inputs"
          exit 1
        fi
        export AWS_ACCESS_KEY_ID="${{ inputs.aws_access_key_id }}"
        export AWS_SECRET_ACCESS_KEY="${{ inputs.aws_secret_access_key }}"
        export AWS_REGION="${{ inputs.aws_region }}"

    # 2. Fetch secrets and export as env variables
    - name: Fetch Secrets from AWS Secrets Manager
      shell: bash
      run: |
        secret_json=$(aws secretsmanager get-secret-value --secret-id "${{ inputs.secret_id }}" --query SecretString --output text)
        # export each key as environment variable
        for key in $(echo "$secret_json" | jq -r 'keys[]'); do
          value=$(echo "$secret_json" | jq -r ".\"$key\"")
          echo "$key=$value" >> $GITHUB_ENV
        done
