name: Auth0 Teardown

on:
  workflow_dispatch: {}

permissions:
  id-token: write   # REQUIRED for OIDC authentication
  contents: read    # needed so checkout can read repo code

env:
  AWS_REGION: eu-west-2

jobs:
  teardown-auth0-config:
    name: Teardown config Auth0
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/auth0

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
        
      - name: Fetch secrets from aws secrets manager
        uses: ./.github/actions/fetch-secrets
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          aws_region: ${{ env.AWS_REGION }}
          secret_id: notes-app-serverless/auth0/pipeline-config

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Destroy (auto-approve)
        run: terraform destroy -auto-approve
