name: Deploy AWS Resources

on:
  workflow_dispatch: {}

env:
  ARTEFACTS_BUCKET_NAME: notes-app-serverless-artefacts-648378716943
  AWS_REGION: eu-west-2

jobs:

  deploy-aws-resources:
    name: Deploy AWS Resources
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/aws

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply (auto-approve)
        run: terraform apply -auto-approve
