name: Infra Teardown E2E

on:
  workflow_dispatch: {}

env:
  AWS_REGION: eu-west-2

jobs:

  teardown-aws-resources:
    name: Teardown aws resources
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infra/aws

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy (auto-approve)
        run: terraform destroy -auto-approve

  teardown-auth0-config:
    name: Teardown config Auth0
    needs: [teardown-aws-resources]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/auth0

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
        
      - name: Fetch secrets from aws secrets manager
        uses: ./.github/actions/fetch-secrets
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          secret_id: notes-app-serverless/auth0/pipeline-config

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Destroy (auto-approve)
        run: terraform destroy -auto-approve

  teardown-bootstrap:
    name: Teardown Bootstrap
    needs: [teardown-auth0-config]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/bootstrap

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Destroy (auto-approve)
        run: terraform destroy -auto-approve